name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - run: yarn prettier --list-different contracts test scripts .github .vscode
      - run: yarn hardhat compile
      - run: yarn hardhat test
