name: CI
  on:
    pull_request:
    push_branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - run: yarn hardhat test